### PR TITLE
Add CI/CD service

### PR DESCRIPTION
**Pull request by liushuyu**
In this PR, CMake and Azure Pipelines configuration files are added to assist the automatic building and releasing binary packages.

Currently, `macOS` and `Windows` builds are added. Actions by the managers of this repository are required to set up Azure Pipelines automation (free for FLOSS projects): https://github.com/marketplace/azure-pipelines#pricing-and-setup.

I am not quite sure how to deliver the Linux binaries since different distributions will use different libraries. One possible solution is to provide the package via Flatpak or Snap.

### CODE REVIEW

**Comment by liushuyu** [comment]
Also, this can partially resolve the task in #2

**Comment by lightbob** [comment]
Thank you for helping out @liushuyu! It seems to me that Azure Pipelines only support repos owned by a user but not ones owned by an organization. It only showed my own repositories in the list of choices but not `trojan-gfw/trojan/qt`. 
I might be able to fork it to my account and start the service. What do you think?

**Comment by GreaterFire** [comment]
Well, I'll try to fix this problem, as usually only the organization owner can add service to an organization.

**Comment by GreaterFire** [comment]
I added the service to this repo.

**Comment by GreaterFire** [comment]
@liushuyu Thanks for your contributions! [Build on macOS](https://github.com/trojan-gfw/trojan-qt/runs/114140841) succeeded while [build on MSVC](https://github.com/trojan-gfw/trojan-qt/runs/114140843) needs some modifications on the code. We'll try to fix this.

**Pull request merged**
